# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-08 16:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('is_right', models.BooleanField()),
                ('score', models.SmallIntegerField()),
                ('created_date', models.DateTimeField()),
                ('update_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.SmallIntegerField(choices=[(1, 'Text'), (2, 'Image'), (3, 'Presentation'), (4, 'Video')])),
                ('created_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('dsc', models.TextField(max_length=500)),
                ('created_date', models.DateTimeField()),
                ('update_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('content', models.TextField(max_length=2000)),
                ('type', models.SmallIntegerField(choices=[(1, 'One answer'), (2, 'Multiple answers'), (3, 'Free text answer')])),
                ('additional_params', django_mysql.models.JSONField(default=dict)),
                ('created_date', models.DateTimeField()),
                ('update_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Spec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='SpecType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('min_score', models.SmallIntegerField()),
                ('max_score', models.SmallIntegerField()),
                ('created_date', models.DateTimeField()),
                ('update_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='TraineeAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_params', django_mysql.models.JSONField(default=dict)),
                ('is_right', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='TraineeLesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pass_date', models.DateTimeField()),
                ('status', models.SmallIntegerField(choices=[(1, 'Not passed'), (2, 'Passed')])),
            ],
        ),
        migrations.CreateModel(
            name='TraineeTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(choices=[(1, ' Not finished'), (2, 'Passed'), (3, 'Failed')])),
                ('pass_date', models.DateTimeField()),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specs.Test')),
            ],
        ),
    ]
