# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 07:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('specs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='traineetest',
            name='trainee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='traineelesson',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specs.Lesson'),
        ),
        migrations.AddField(
            model_name='traineelesson',
            name='trainee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='traineeanswer',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specs.Answer'),
        ),
        migrations.AddField(
            model_name='traineeanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specs.Question'),
        ),
        migrations.AddField(
            model_name='traineeanswer',
            name='trainee_test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specs.TraineeTest'),
        ),
        migrations.AddField(
            model_name='test',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specs.Lesson'),
        ),
        migrations.AddField(
            model_name='test',
            name='trainee',
            field=models.ManyToManyField(through='specs.TraineeTest', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='spec',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specs.SpecType'),
        ),
        migrations.AddField(
            model_name='question',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specs.Test'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='spec',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specs.Spec'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='trainee',
            field=models.ManyToManyField(through='specs.TraineeLesson', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attachment',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specs.Lesson'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specs.Question'),
        ),
    ]
