# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 14:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('specs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='dsc',
            field=models.TextField(max_length=500, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='iframe_link',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ссылка на iframe'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='spec',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specs.Spec', verbose_name='Специализация'),
        ),
        migrations.AlterField(
            model_name='test',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specs.Lesson', verbose_name='Урок'),
        ),
        migrations.AlterField(
            model_name='test',
            name='max_score',
            field=models.SmallIntegerField(verbose_name='Максимальный балл'),
        ),
        migrations.AlterField(
            model_name='test',
            name='min_score',
            field=models.SmallIntegerField(verbose_name='Минимальный проходной балл'),
        ),
        migrations.AlterField(
            model_name='test',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
    ]
