# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-14 18:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('specs', '0002_auto_20170706_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='spec',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specs.Spec', verbose_name='Специальность'),
        ),
        migrations.AlterField(
            model_name='traineeanswer',
            name='additional_params',
            field=django_mysql.models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
