# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='address',
            field=models.CharField(max_length=200, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='dsc',
            field=models.TextField(max_length=2000, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='is_remote',
            field=models.BooleanField(default=False, verbose_name='Удаленность'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='spec',
            field=models.ManyToManyField(to='specs.Spec', verbose_name='Специальности'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='type',
            field=models.SmallIntegerField(choices=[(1, 'Full time'), (2, 'Part time'), (3, 'Single project')], verbose_name='Тип'),
        ),
    ]
