# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0002_auto_20170706_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='type',
            field=models.SmallIntegerField(choices=[(1, 'Полная'), (2, 'Частичная'), (3, 'Проектная')], verbose_name='Тип'),
        ),
    ]
